[project]
name = "textual-mastermind"
version = "3.1.0"
description = "Mastermind game built with Textual"
authors = [{ name = "Rafal Padkowski", email = "rafaelp@poczta.onet.pl" }]
requires-python = ">=3.14"
readme = "README.md"
dependencies = [
    "textual>=8.2.8",
    "textual-utils>=2.3.0",
    "tilsit-config>=1.0.1",
    "tilsit-i18n>=1.0.0",
]

[project.scripts]
mm = "textual_mastermind:main"

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

