[project]
name = "textual-mastermind"
version = "4.0.2"
description = "Mastermind game built with Textual"
authors = [{ name = "Rafal Padkowski", email = "rafaelp@poczta.onet.pl" }]
requires-python = ">=3.14"
readme = "README.md"
dependencies = [
    "textual>=8.2.8",
    "tomlkit>=0.15.1",
]

[project.scripts]
mm = "textual_mastermind:main"

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
