[ui]
main_icon = "❔"
new_game_icon = "📜"
code_blank_symbol = "-"
code_symbols = ["R", "G", "B", "O", "Y", "W", "C", "M"]
code_colors = ["tomato", "green", "cornflowerblue", "orange", "yellow", "white", "cyan", "fuchsia"]
feedback_blank_symbol = "-"
feedback_symbols = ["w", "r"]
feedback_colors = ["tomato", "white"]
style = ""

[variations]
[variations.original]
num_rows = 10
num_pegs = 4
num_symbols = 6

[variations.mini]
num_rows = 6
num_pegs = 4
num_symbols = 6

[variations.super]
num_rows = 12
num_pegs = 5
num_symbols = 8

[settings]
[settings.variation]
default_value = "original"
current_value = "original"

[settings.blank_symbol]
default_value = false
current_value = false

[settings.duplicate_symbols]
default_value = false
current_value = false
