[ui]
main_icon = "❔"
title = "Mastermind"
new_game_icon = "📜"
code_blank_letter = "-"
code_letters = ["R", "G", "B", "O", "Y", "W", "S", "V"]
code_colors = ["red", "lawngreen", "deepskyblue", "orange", "yellow", "white", "ansi_bright_black", "violet"]
code_style = ""
feedback_blank_letter = "-"
feedback_letters = ["r", "w"]
feedback_colors = ["red", "white"]
feedback_style = ""

[variations]
[variations.original]
num_rows = 10
num_pegs = 4
num_colors = 6

[variations.mini]
num_rows = 6
num_pegs = 4
num_colors = 6

[variations.super]
num_rows = 12
num_pegs = 5
num_colors = 8

[settings]
[settings.variation_name]
default_value = "original"
current_value = "original"

[settings.allow_blank_color]
default_value = false
current_value = false

[settings.allow_duplicate_colors]
default_value = false
current_value = false
